### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by rtate2** [rtate2/ClickedIn#6]
**Profile**
- id
- Clinker
- Friends (list of clinkers)  == homie
- Enemies (list of clinkers)  == enemy

**Relationship**
- id
- Clinker id
- Clinker id
- Homie or Enemy

**Clinker**
- Id
- Number
- Street name
- Services
- Interests

Services (enum)
Interests (enum)

**Comment by rarceneaux** [comment]
![image](https://user-images.githubusercontent.com/40898992/78728137-3258e600-78fc-11ea-922d-41f57f48093e.png)

**Comment by kelsey-21** [comment]
![image](https://user-images.githubusercontent.com/54123694/79048163-c2d74500-7be0-11ea-81f2-c907c40ee867.png)
